## Configuration
_Initial steps to get the notebook ready to play nice with our repository. Do not delete this section._

Code formatting with [black](https://pypi.org/project/nb-black/).

Add our `utils` directory to the system's `$PATH` so we can import Python files from sibling directories.

In [1]:
import os
import pathlib

In [2]:
this_dir = pathlib.Path(os.path.abspath(""))

In [3]:
data_dir = this_dir / "data"

In [4]:
import pytz
import glob
import requests
import pandas as pd
from slugify import slugify
from datetime import datetime, date

/Users/slee/.local/share/virtualenvs/california-coronavirus-scrapers-QTClc1WQ/lib/python3.8/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

## Download

In [5]:
url = "https://services5.arcgis.com/ROBnTHSNjoZ2Wm1P/ArcGIS/rest/services/COVID_19_Case_Rates_by_Zip_Code_WM/FeatureServer/0/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token="

In [6]:
r = requests.get(url)

In [7]:
data = r.json()

## Parse

In [8]:
values = []

In [9]:
for f in data["features"]:
    row = f["attributes"].values()
    values.append(row)

In [10]:
cols = list(data["features"][0]["attributes"].keys())

Convert to dataframe

In [11]:
df = pd.DataFrame(values, columns=cols)

Get timestamp

In [12]:
date_url = "https://services5.arcgis.com/ROBnTHSNjoZ2Wm1P/ArcGIS/rest/services/COVID_19_Case_Rates_by_Zip_Code_WM/FeatureServer/0/?f=json"

In [13]:
date_r = requests.get(date_url)

In [14]:
date_data = date_r.json()

In [15]:
timestamp = date_data["editingInfo"]["lastEditDate"]

In [16]:
timestamp = datetime.fromtimestamp((timestamp / 1000))

In [17]:
timestamp

datetime.datetime(2023, 2, 24, 3, 37, 30, 121000)

In [18]:
update_date = pd.to_datetime(timestamp).round(freq='S')

In [19]:
update_date

Timestamp('2023-02-24 03:37:30')

Add the timestamp to the dataframe

In [20]:
df["county_date"] = update_date

In [21]:
df

,Zip_Number,Zip_Alpha,Population,Cases,CaseRates,GlobalID,OBJECTID,Shape__Area,Shape__Length,county_date
0,94502,94502,14061,2107,14984.709480,2201afb0-f24a-4caa-a280-7b078e60745a,1,1.032795e+07,14675.181018,2023-02-24 03:37:30
1,94706,94706,20331,3027,14888.593773,17902952-3a86-466c-9d24-ac3111f571aa,2,5.654830e+06,13201.790210,2023-02-24 03:37:30
2,94709,94709,11734,1791,15263.337310,6385fe10-a831-42df-9145-4d33725a691a,3,2.347100e+06,7845.460234,2023-02-24 03:37:30
3,94710,94710,8458,2128,25159.612201,a968be73-65c9-4d4a-96ee-825e20a407c0,4,1.132117e+07,34031.634584,2023-02-24 03:37:30
4,94587,94587,72559,17028,23467.798619,7da97736-e2af-4136-8312-842821133991,5,1.200952e+08,86993.659936,2023-02-24 03:37:30
5,94577,94577,48690,12212,25081.125488,4e279009-0fd3-405a-afca-2b1f9c2ecf35,6,3.364755e+07,48564.165519,2023-02-24 03:37:30
6,94605,94605,42945,11246,26186.983351,778ec18a-f365-4942-af43-6a8377e3834e,7,3.629375e+07,36745.169765,2023-02-24 03:37:30
7,94606,94606,37481,8953,23886.769296,79272129-630e-4d06-9fdf-0956e7fa8b7d,8,9.712934e+06,20368.808704,2023-02-24 03:37:30
8,94608,94608,32602,7283,22339.120299,803f9089-a635-4eb0-b1b8-00db378a418b,9,1.152262e+07,22652.244258,2023-02-24 03:37:30
9,94610,94610,30892,5977,19348.051275,ee76320b-b507-407b-88fb-cdde5582965c,10,8.594601e+06,21468.664491,2023-02-24 03:37:30
10,94702,94702,16364,3500,21388.413591,4e9b7501-f5c3-4f71-a16e-98cda80035d6,11,5.027837e+06,13308.191821,2023-02-24 03:37:30
11,94703,94703,20296,3943,19427.473394,c394e167-339a-4690-a1ea-07ad69cdcd39,12,5.606830e+06,13984.221313,2023-02-24 03:37:30
12,94704,94704,30116,5389,17894.142648,fe0f9c53-1449-4b74-a55d-a68dea79ac8c,13,5.488663e+06,15248.250799,2023-02-24 03:37:30
13,94705,94705,12914,2232,17283.568221,fd4eb288-b051-479d-b9d9-44ca951680a2,14,8.244548e+06,19783.496428,2023-02-24 03:37:30
14,94720,94720,1466,1212,82673.942701,cec7c4a4-e294-4566-9254-48e6b1461878,15,6.752215e+06,13864.662901,2023-02-24 03:37:30
15,94568,94568,68661,14481,21090.575436,8f607b79-44e9-4165-a6d3-bd9ae2b6033e,16,5.744693e+07,52270.144454,2023-02-24 03:37:30
16,94707,94707,9445,1231,13033.350979,76e49195-07fd-4499-94af-9c2286d2dccc,17,4.763095e+06,11912.623643,2023-02-24 03:37:30
17,94501,94501,63522,12304,19369.667202,37d562a3-6f68-470b-b732-ce299e330632,18,3.375291e+07,44844.878432,2023-02-24 03:37:30
18,94619,94619,23664,5476,23140.635565,99968dea-f892-4edb-820b-82dcbd7f8014,19,2.059026e+07,37098.699390,2023-02-24 03:37:30
19,94607,94607,28264,6886,24363.147467,702575a6-fd4d-48b4-9b69-b55f7891d939,20,2.482065e+07,41770.153847,2023-02-24 03:37:30
20,94609,94609,23421,5381,22975.107809,a1aad017-8dc6-4b43-a77c-cc5d6bceed5c,21,7.220802e+06,16279.212615,2023-02-24 03:37:30
21,94612,94612,19181,4335,22600.490068,c4fb8d52-9a46-491a-a1cb-c99719bee4fb,22,4.643602e+06,12632.025840,2023-02-24 03:37:30
22,94618,94618,15947,2396,15024.769549,2df87f8b-7db8-41af-85ec-6fde1c4b1360,23,9.583396e+06,24226.220545,2023-02-24 03:37:30
23,94601,94601,53676,16771,31244.876667,30555e42-f863-4f01-a25b-7c1c292f1472,24,1.403409e+07,18711.143227,2023-02-24 03:37:30
24,94602,94602,30240,6201,20505.952381,ae933949-abbb-46e2-9e60-a716b72b176a,25,1.369260e+07,22400.761700,2023-02-24 03:37:30
25,94611,94611,37425,6821,18225.784903,d4ffcd67-0685-4723-a33c-421bc709ec7a,26,3.028469e+07,45945.747650,2023-02-24 03:37:30
26,94603,94603,32296,11848,36685.657667,d5ea407c-4f6d-4b6f-9ea5-8e1ca7bbcf50,27,1.153565e+07,22222.900411,2023-02-24 03:37:30
27,94621,94621,31847,11520,36172.951926,bb4ad57e-0992-4960-9ca5-2877a5ce3c55,28,3.488154e+07,53738.607584,2023-02-24 03:37:30
28,94588,94588,32788,6019,18357.325851,8e5c0312-1ffe-4c80-b1a5-95420c502b1d,29,1.052295e+08,97678.716085,2023-02-24 03:37:30
29,94536,94536,73121,14048,19211.991083,72ef0e3f-2041-4b78-aba3-e3c527dd36d3,30,5.633439e+07,42798.755758,2023-02-24 03:37:30
30,94555,94555,38582,6228,16142.242496,219569bf-7703-4a5f-a6ec-715a7c4273a5,31,4.746045e+07,42193.548528,2023-02-24 03:37:30
31,94551,94551,40466,9058,22384.223793,545b6af1-801a-48c5-ae0d-356b125e2a10,32,1.914284e+08,83604.398910,2023-02-24 03:37:30
32,94566,94566,47061,7228,15358.789656,ba878c5e-9daf-4b5b-834c-fd0da9775040,33,8.631722e+07,53025.300351,2023-02-24 03:37:30
33,94550,94550,50668,9625,18996.210626,3d82f3ba-3ca9-4aa0-a4da-397ae44de66f,34,9.791136e+08,185498.585022,2023-02-24 03:37:30
34,94541,94541,67027,19774,29501.544154,a84ebdaf-3764-4297-a8f8-e438758f7805,35,2.942270e+07,41195.103063,2023-02-24 03:37:30
35,94542,94542,14094,3102,22009.365688,cf9f42a8-0ba7-402b-9c70-db52cfd46274,36,3.382890e+07,38919.021392,2023-02-24 03:37:30
36,94544,94544,78780,24142,30644.833714,9a98af1f-ad93-4a4b-b0a8-962711e53453,37,4.398904e+07,42187.854785,2023-02-24 03:37:30
37,94545,94545,32533,9394,28875.295853,4b374f56-53ff-44fd-a74b-31dff1debded,38,5.288843e+07,41985.678010,2023-02-24 03:37:30
38,94552,94552,15034,2480,16495.942530,0795f767-4c9f-4a22-a616-aa0a487f0941,39,1.616083e+08,109693.707947,2023-02-24 03:37:30
39,94578,94578,41044,11445,27884.709093,05d0a885-f08d-4dd0-8231-3dc871b00a1f,40,1.867120e+07,32831.158476,2023-02-24 03:37:30
40,94579,94579,20385,5666,27794.947265,ae171935-b21c-46d0-a1ee-a8a089d0935e,41,1.284185e+07,21741.748742,2023-02-24 03:37:30
41,94580,94580,30055,8293,27592.746631,52475738-187d-45be-93f9-cf1ed8eae248,42,1.592159e+07,26486.126410,2023-02-24 03:37:30
42,94546,94546,44888,9850,21943.503832,c524d940-c6b2-471b-8be4-b093ffd4241b,43,1.104949e+08,71903.183646,2023-02-24 03:37:30
43,94560,94560,49183,12236,24878.514934,22955e8a-f51f-434c-a570-825fbceb4ed0,44,7.860635e+07,48191.921999,2023-02-24 03:37:30
44,94538,94538,66369,14733,22198.616824,1c78d8cb-4e1c-4c27-9fd6-4b9aca710ea6,45,9.858148e+07,85042.112913,2023-02-24 03:37:30
45,94708,94708,9131,1146,12550.651626,a4fa7e6f-dd72-4fe7-b3d7-b10c49183736,46,5.852437e+06,13895.509757,2023-02-24 03:37:30
46,94539,94539,55093,8021,14559.018387,910c6d39-6b05-4b4c-9c8c-a831730047e9,47,1.215879e+08,65094.925039,2023-02-24 03:37:30
47,94586,94586,1041,151,14505.283381,9e6315bc-d754-4e09-b5ba-feba5e190996,48,1.253197e+08,106105.582265,2023-02-24 03:37:30
48,95391,95391,132,1,757.575758,babff81a-76ac-4cd6-a400-3ad948565194,49,3.228203e+07,35796.231998,2023-02-24 03:37:30
49,94613,94613,732,8,1092.896175,7a93b001-a991-4c70-8eb2-a5447f1cd1ac,50,9.896379e+05,4499.407176,2023-02-24 03:37:30
50,94514,94514,59,2,3389.830508,08f69ded-a10a-42a0-b6bf-b1a3a3c8701d,51,6.763554e+07,41982.874112,2023-02-24 03:37:30
51,94505,94505,71,2,2816.901408,c7a9e46c-7cfb-4102-bdbd-3c0c1d23792d,52,3.427089e+06,8237.632496,2023-02-24 03:37:30
52,95377,95377,64,1,1562.500000,3e8067c4-631a-47d7-9f10-f2e388ea74c5,53,5.189378e+07,35234.088583,2023-02-24 03:37:30

Rename and trim

In [22]:
clean_df = df[["Zip_Alpha", "Cases", "county_date"]].rename(
    columns={"Zip_Alpha": "zip", "Cases": "confirmed_cases"}
)

Match city names to zips

In [23]:
zips = [
    "94502",
    "94577",
    "94579",
    "94603",
    "94605",
    "94621",
    "94501",
    "94606",
    "94607",
    "94610",
    "94612",
    "94608",
    "94609",
    "94618",
    "94702",
    "94703",
    "94704",
    "94705",
    "94709",
    "94710",
    "94720",
    "94601",
    "94602",
    "94611",
    "94613",
    "94619",
    "94706",
    "94707",
    "94708",
    "94538",
    "94555",
    "94560",
    "94539",
    "94550",
    "94536",
    "94542",
    "94544",
    "94545",
    "94587",
    "94541",
    "94546",
    "94552",
    "94578",
    "94580",
    "94566",
    "94568",
    "94586",
    "94588",
    "94551",
    "95391",
    "94514",
    "94505",
    "95377",
]

In [24]:
cities = [
    "Alameda",
    "San Leandro",
    "San Leandro",
    "Oakland",
    "Oakland",
    "Oakland",
    "Alameda",
    "Oakland",
    "Oakland",
    "Oakland",
    "Oakland",
    "Emeryville",
    "Oakland",
    "Oakland",
    "Berkeley",
    "Berkeley",
    "Berkeley",
    "Berkeley",
    "Berkeley",
    "Berkeley",
    "Berkeley",
    "Oakland",
    "Oakland",
    "Oakland",
    "Oakland",
    "Oakland",
    "Albany",
    "Berkeley",
    "Berkeley",
    "Fremont",
    "Fremont",
    "Newark",
    "Fremont",
    "Livermore",
    "Fremont",
    "Hayward",
    "Hayward",
    "Hayward",
    "Union City",
    "Hayward",
    "Castro Valley",
    "Castro Valley",
    "San Leandro",
    "San Lorenzo",
    "Pleasanton",
    "Dublin",
    "Sunol",
    "Pleasanton",
    "Livermore",
    "Mountain House",
    "Byron",
    "Discovery Bay",
    "Tracy",
]

In [25]:
d = {"zip": zips, "city": cities}

In [26]:
matchup_df = pd.DataFrame(d)

In [27]:
merge_df = pd.merge(clean_df, matchup_df, how="left", on="zip")

In [28]:
merge_df["area"] = merge_df["zip"] + ": " + merge_df["city"]

Clean up

In [29]:
merge_df["county"] = "Alameda"

In [30]:
merge_df = merge_df[["county", "area", "county_date", "confirmed_cases"]]

Drop mysterious blank rows

In [31]:
filter_df = merge_df.dropna(subset=["area"])

Fill empty cases with 0

In [32]:
filter_df["confirmed_cases"] = filter_df.confirmed_cases.fillna(0)

Filter down to the latest date

In [33]:
export_df = filter_df[filter_df.county_date == filter_df.county_date.max()]

## Vet

In [34]:
try:
    assert not len(export_df) > 53
except AssertionError:
    raise AssertionError("Alameda scraper has additional rows than before")

In [35]:
try:
    assert not len(export_df) < 53
except AssertionError:
    raise AssertionError("Alameda County scraper is missing rows")

In [36]:
export_df

     county                   area         county_date  confirmed_cases
0   Alameda         94502: Alameda 2023-02-24 03:37:30             2107
1   Alameda          94706: Albany 2023-02-24 03:37:30             3027
2   Alameda        94709: Berkeley 2023-02-24 03:37:30             1791
3   Alameda        94710: Berkeley 2023-02-24 03:37:30             2128
4   Alameda      94587: Union City 2023-02-24 03:37:30            17028
5   Alameda     94577: San Leandro 2023-02-24 03:37:30            12212
6   Alameda         94605: Oakland 2023-02-24 03:37:30            11246
7   Alameda         94606: Oakland 2023-02-24 03:37:30             8953
8   Alameda      94608: Emeryville 2023-02-24 03:37:30             7283
9   Alameda         94610: Oakland 2023-02-24 03:37:30             5977
10  Alameda        94702: Berkeley 2023-02-24 03:37:30             3500
11  Alameda        94703: Berkeley 2023-02-24 03:37:30             3943
12  Alameda        94704: Berkeley 2023-02-24 03:37:30             5389
13  Alameda        94705: Berkeley 2023-02-24 03:37:30             2232
14  Alameda        94720: Berkeley 2023-02-24 03:37:30             1212
15  Alameda          94568: Dublin 2023-02-24 03:37:30            14481
16  Alameda        94707: Berkeley 2023-02-24 03:37:30             1231
17  Alameda         94501: Alameda 2023-02-24 03:37:30            12304
18  Alameda         94619: Oakland 2023-02-24 03:37:30             5476
19  Alameda         94607: Oakland 2023-02-24 03:37:30             6886
20  Alameda         94609: Oakland 2023-02-24 03:37:30             5381
21  Alameda         94612: Oakland 2023-02-24 03:37:30             4335
22  Alameda         94618: Oakland 2023-02-24 03:37:30             2396
23  Alameda         94601: Oakland 2023-02-24 03:37:30            16771
24  Alameda         94602: Oakland 2023-02-24 03:37:30             6201
25  Alameda         94611: Oakland 2023-02-24 03:37:30             6821
26  Alameda         94603: Oakland 2023-02-24 03:37:30            11848
27  Alameda         94621: Oakland 2023-02-24 03:37:30            11520
28  Alameda      94588: Pleasanton 2023-02-24 03:37:30             6019
29  Alameda         94536: Fremont 2023-02-24 03:37:30            14048
30  Alameda         94555: Fremont 2023-02-24 03:37:30             6228
31  Alameda       94551: Livermore 2023-02-24 03:37:30             9058
32  Alameda      94566: Pleasanton 2023-02-24 03:37:30             7228
33  Alameda       94550: Livermore 2023-02-24 03:37:30             9625
34  Alameda         94541: Hayward 2023-02-24 03:37:30            19774
35  Alameda         94542: Hayward 2023-02-24 03:37:30             3102
36  Alameda         94544: Hayward 2023-02-24 03:37:30            24142
37  Alameda         94545: Hayward 2023-02-24 03:37:30             9394
38  Alameda   94552: Castro Valley 2023-02-24 03:37:30             2480
39  Alameda     94578: San Leandro 2023-02-24 03:37:30            11445
40  Alameda     94579: San Leandro 2023-02-24 03:37:30             5666
41  Alameda     94580: San Lorenzo 2023-02-24 03:37:30             8293
42  Alameda   94546: Castro Valley 2023-02-24 03:37:30             9850
43  Alameda          94560: Newark 2023-02-24 03:37:30            12236
44  Alameda         94538: Fremont 2023-02-24 03:37:30            14733
45  Alameda        94708: Berkeley 2023-02-24 03:37:30             1146
46  Alameda         94539: Fremont 2023-02-24 03:37:30             8021
47  Alameda           94586: Sunol 2023-02-24 03:37:30              151
48  Alameda  95391: Mountain House 2023-02-24 03:37:30                1
49  Alameda         94613: Oakland 2023-02-24 03:37:30                8
50  Alameda           94514: Byron 2023-02-24 03:37:30                2
51  Alameda   94505: Discovery Bay 2023-02-24 03:37:30                2
52  Alameda           95377: Tracy 2023-02-24 03:37:30                1

## Export

Mark the current date

In [37]:
tz = pytz.timezone("America/Los_Angeles")

In [38]:
today = datetime.now(tz).date()

In [39]:
slug = slugify("Alameda")

In [40]:
export_df.to_csv(data_dir / slug / f"{today}.csv", index=False)

## Combine

In [41]:
csv_list = [
    i
    for i in glob.glob(str(data_dir / slug / "*.csv"))
    if not str(i).endswith("timeseries.csv")
]

In [42]:
df_list = []
for csv in csv_list:
    if "manual" in csv:
        df = pd.read_csv(csv, parse_dates=["date"])
    else:
        file_date = csv.split("/")[-1].replace(".csv", "")
        df = pd.read_csv(csv, parse_dates=["county_date"])
        df["date"] = file_date
    df_list.append(df)

In [43]:
df = pd.concat(df_list).sort_values(["date", "area"])

In [44]:
df.to_csv(os.path.join(data_dir / slug / "timeseries.csv"), index=False)

In [48]:
df.tail(20)

,county,area,county_date,confirmed_cases,date
20,Alameda,94609: Oakland,2023-02-24 03:37:30,5381,2023-02-24
9,Alameda,94610: Oakland,2023-02-24 03:37:30,5977,2023-02-24
25,Alameda,94611: Oakland,2023-02-24 03:37:30,6821,2023-02-24
21,Alameda,94612: Oakland,2023-02-24 03:37:30,4335,2023-02-24
49,Alameda,94613: Oakland,2023-02-24 03:37:30,8,2023-02-24
22,Alameda,94618: Oakland,2023-02-24 03:37:30,2396,2023-02-24
18,Alameda,94619: Oakland,2023-02-24 03:37:30,5476,2023-02-24
27,Alameda,94621: Oakland,2023-02-24 03:37:30,11520,2023-02-24
10,Alameda,94702: Berkeley,2023-02-24 03:37:30,3500,2023-02-24
11,Alameda,94703: Berkeley,2023-02-24 03:37:30,3943,2023-02-24
12,Alameda,94704: Berkeley,2023-02-24 03:37:30,5389,2023-02-24
13,Alameda,94705: Berkeley,2023-02-24 03:37:30,2232,2023-02-24
1,Alameda,94706: Albany,2023-02-24 03:37:30,3027,2023-02-24
16,Alameda,94707: Berkeley,2023-02-24 03:37:30,1231,2023-02-24
45,Alameda,94708: Berkeley,2023-02-24 03:37:30,1146,2023-02-24
2,Alameda,94709: Berkeley,2023-02-24 03:37:30,1791,2023-02-24
3,Alameda,94710: Berkeley,2023-02-24 03:37:30,2128,2023-02-24
14,Alameda,94720: Berkeley,2023-02-24 03:37:30,1212,2023-02-24
52,Alameda,95377: Tracy,2023-02-24 03:37:30,1,2023-02-24
48,Alameda,95391: Mountain House,2023-02-24 03:37:30,1,2023-02-24

In [45]:
# df = pd.read_csv(os.path.join(data_dir / slug / "timeseries.csv"), parse_dates=["county_date"])
# df["date"] = pd.to_datetime(df.date, format= "%Y-%m-%d %H:%M:%S")
# df["date"] =  df['date'].dt.strftime('%Y-%m-%d %H:%M:%S')
# df.to_csv(os.path.join(data_dir / slug / "timeseries.csv"), index=False)